### ISSUE TITLE
Unable to remove velruse plugin to be able to update to Plone 5+

### ISSUE THREAD

**Issue by canepan** [RedTurtle/pas.plugins.velruse#2]
Hi, I am trying to upgrade my Plone 4.3 site to version 5 (or even 6, since now it's out of beta), but if I build without the velruse plugin, it fails with some stacktraces.
Is there a way to uninstall the plugin, possibly before copying the Data.fs file to the new installation?
I already disabled it through the addon configuration (prefs_install_products_form)

Thank you for any help or pointer

**Comment by cekk** [comment]
Yes, there is a missing uninstall profile.
There are some things that are registered in the default profile, but needs to be removed on uninstall step.

Are you able to handle it and create a pull-request?

**Comment by canepan** [comment]
Unfortunately I wasn't able to get over it.
The error I get is:
```
2022-12-19 09:17:48 ERROR ZODB.Connection Couldn't load state for 0x3590
Traceback (most recent call last):
  File "/mnt/opt/Plone-4.3.18/buildout-cache/eggs/ZODB3-3.10.7-py2.7-linux-aarch64.egg/ZODB/Connection.py", line 860, in setstate
    self._setstate(obj)
  File "/mnt/opt/Plone-4.3.18/buildout-cache/eggs/ZODB3-3.10.7-py2.7-linux-aarch64.egg/ZODB/Connection.py", line 914, in _setstate
    self._reader.setGhostState(obj, p)
  File "/mnt/opt/Plone-4.3.18/buildout-cache/eggs/ZODB3-3.10.7-py2.7-linux-aarch64.egg/ZODB/serialize.py", line 612, in setGhostState
    state = self.getState(pickle)
  File "/mnt/opt/Plone-4.3.18/buildout-cache/eggs/ZODB3-3.10.7-py2.7-linux-aarch64.egg/ZODB/serialize.py", line 605, in getState
    return unpickler.load()
  File "/usr/lib/python2.7/copy_reg.py", line 48, in _reconstructor
    obj = object.__new__(cls)
TypeError: object.__new__(VelruseBackendConfig) is not safe, use Persistence.Persistent.__new__()
```
